### ISSUE TITLE
run_sql_query method

### ISSUE THREAD

**Issue by thekenz** [looker/lookr#12]
Be able to create a SQL query in Looker, and pull that data into LookR using URL parameters found in the generated SQL Query.

**Comment by maxcorbin** [comment]
This scares me

**Comment by githoov** [comment]
How so?

**Comment by thekenz** [comment]
Max was thinking that this function could possibly introduce a way for people to sidestep not having a SQL Runner permission. But the way that I'm thinking about implementing this forces people to go through SQL Runner to access the data.

**Comment by githoov** [comment]
mmmmhm

**Comment by maxcorbin** [comment]
Closing, I don't think this is supported by our API at a more basic level
