### ISSUE TITLE
Error loading package

### ISSUE THREAD

**Issue by GShotwell** [looker/lookr#13]
I'm having some trouble loading the package on OS X 10.11.5 (15F34), RStudio  0.99.903, I get this error when I try to load the Lookr package: 

```
JavaVM: requested Java version ((null)) not available. Using Java at "" instead.
JavaVM: Failed to load JVM: /bundle/Libraries/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
Error : .onLoad failed in loadNamespace() for 'LookR', details:
  call: .jinit()
  error: JNI_GetCreatedJavaVMs returned -1

Error: package or namespace load failed for ‘LookR’
```

rJava loads successfully, and I'm out of ideas. Any thoughts?

**Comment by maxcorbin** [comment]
Hey @GShotwell, sorry you're running into trouble here! Can you let me know what version of R you're running and what your JAVA_PATH variable is set to?

**Comment by maxcorbin** [comment]
I have run into this problem a couple of times and use the guide here to resolve it, this seems to be a problem generally with Java 8 and Mac OS X, so we'll be looking for ways to work around this in the long-term: https://oliverdowling.com.au/2014/03/28/java-se-8-on-mac-os-x/

Let me know whether that guide helped, I'll probably be writing a script to do this soon.

**Comment by GShotwell** [comment]
@maxcorbin I'm on R v 3.3.1, I'm not sure how to check my JAVA_PATH variable

I'll give that Java set up a try, but have you all thought about building an R package which doesn't have the Java dependency? It seems like `httr` would provide the same functionality without causing people so much set up trouble.

**Comment by githoov** [comment]
@GShotwell The idea behind all of the Java dependencies was this: Looker's API has been, and continues to be, in a state of constant change. Rather than write a package that directly handles authentication and hits the various REST endpoints, we wanted to rely on the fact that we can generate SDKs/clients programmatically using Swagger. That way the LookR maintenance component would be relatively minimal. Now, instead of trying to keep up with API changes, we can simply regenerate a Swagger SDK (_e.g._, in Java) and slot it into a harness of sorts. The tradeoff, quite clearly, is that configuring one's Java environment can be painful.

As the architect of this approach, my gut reaction is to defend it. However, I'm also prepared to state that it is imperfect. If there's clearly a better solution that reduces pain for the user and that is associated a reasonable amount of development, I'm an advocate for that.

**Comment by GShotwell** [comment]
I see, that makes a lot of sense. 

My impression from the R community is that there's a tendency to try to avoid this kind of dependency if possible. The reason is just that (relative to other programmers) a lot of R users are super uncomfortable with set-up processes which require them to open up their terminal, and often abandon things which don't work out of the box from a CRAN or github installation. So the package might get better uptake if it avoided the rJava dependency.

**Comment by maxcorbin** [comment]
@GShotwell Closing this issue, but I think you have a point re: non-Java dependent solutions. I've got some plans around this.

FYI, my resources for troubleshooting this package usually are from packages like `xlsx` and other R packages that are on CRAN that run into Java issues, if you need more help configuring things properly.

Thanks for the feedback here, feel free to open a new issue or message me directly if you need any help configuring the Java environment.

**Comment by GShotwell** [comment]
Thanks for the offer, I ended up just writing an internal package around the REST api because I think it suits our needs a bit better. I'd be happy to open source the package if you want to go the REST route.

**Comment by chrispatrickcville** [comment]
Hi, I'm having a similar issue. I'm able to install/load rJava and other packages that have rJava dependencies (xlsx) but can't figure out how to address the issue with lookr. `Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Error : package ‘rJava’ could not be loaded
ERROR: lazy loading failed for package ‘LookR’`

**Comment by chrispatrickcville** [comment]
I was able to resolve my issue by running the following in my terminal:
```
cd /Library/Frameworks/R.framework/Versions/3.4/Resources/lib
ln -s /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/server/libjvm.dylib libjvm.dylib
```

**Comment by maxcorbin** [comment]
@chrispatrickcville Yeah, you're on to something there, I was able to fix this on my end using the directions posted on this blog post: https://oliverdowling.com.au/2014/03/28/java-se-8-on-mac-os-x/comment-page-1/

The following commands should work for Mac OS X High Sierra, and I think also all the way back to Yosemite, though this requires more testing:

```
mkdir -p $(/usr/libexec/java_home)/bundle/Libraries
ln -s  $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib $(/usr/libexec/java_home)/bundle/Libraries/libserver.dylib
```

You may have to use super user (`sudo`) for this

**Comment by maxcorbin** [comment]
I'm closing this as solved since this seems to have a solution outside of changes to LookR, please comment if you are still running into this
