### ISSUE TITLE
Can't install devtools package on windows

### ISSUE THREAD

**Issue by sunny2nyc** [looker/lookr#14]
Hi Maxie,

I tried to install package "devtools" and get below error message:
![error](https://cloud.githubusercontent.com/assets/22156610/18448502/6a9a7738-78f9-11e6-9cb0-9f5ce1691739.PNG)

When I install the package, I choose USA (MI) as my cran. I'm in New York, I'll try to select another cran to see. and could you advise me how to download these errored dependencies seperately?

Thank you so much for your help and let me know in case of any concerns. Have a nice one!

Best regards,
Sunny

**Comment by sunny2nyc** [comment]
Hi Maxie, I deleted my r and downloaded a new one, now I can install the package successfully. It's just when I try to install github, I get below error:
![error](https://cloud.githubusercontent.com/assets/22156610/18448753/45da73e8-78fa-11e6-94c7-54ea2e6b7c74.PNG)
Shall I download "rjava" seperately?

Thanks, 
Sunny

**Comment by maxcorbin** [comment]
Hey @sunny2nyc this looks like a pretty classic issue with your Java environment. It looks like your `JAVA_HOME` variable is not set. When you install RTools, you should be given an opportunity to let RTools know that you want it to update your JAVA_HOME environmental variable and registry entry. You should try checking that off during installation of RTools, let me know if you do this and the problem persists.

**Comment by maxcorbin** [comment]
If that doesn't work, you can try following this guide: https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html

**Comment by sunny2nyc** [comment]
Hi @maxcorbin, it's a shame that it's my first time using Java, confused on a lot of things. Do you mean check below box:
![image](https://cloud.githubusercontent.com/assets/22156610/18451263/34d5d1e6-7904-11e6-8fa7-cbcf802b2a8a.png)

Thanks,
Sunny

**Comment by sunny2nyc** [comment]
@maxcorbin want to ask you a separate question, the last step is bring analytic results from R to looker. I googled the info and found sample codes for redshift:

writeToDatabase <-function(dataframe,date){
  #How to write the final data back to a databse 
  # NOTE THIS IS HOW TO DO IT FOR REDSHIFT ONLY!!!! FOR OTHER DATABASES, PLEASE SEARCH FOR THE APPROPRIATE API ONLINE
  dataframe$score_date <- rep(date,nrow(dataframe))
  print("Getting driver...")
  driver <- JDBC("com.amazon.redshift.jdbc41.Driver", "RedshiftJDBC41-1.1.9.1009.jar", identifier.quote="`")
  url <- "jdbc:redshift://MYCOMPANY-REDSHIFT-URL:5439/mycompany?user=USERNAME&password=MYPASSWORD" 
  #Put the correct port number after the URL string
  print("Done.")
  
  print("Establishing connection...")
  con <- dbConnect(driver, url)
  print("Done.")
  
  print("Writing to DB...")
  dbWriteTable(con, "public.my_predictions_table", dataframe, overwrite=FALSE, append=TRUE) #set these parameters to 
  dbDisconnect(con)
  print("Done.")

}

We are using ode.net. I'm wondering could you share some sample code for this type of database. I couldn't find anything useful.

Thank you so much!

Best regards,
Sunny

**Comment by sunny2nyc** [comment]
Hi @maxcorbin, I'm guessing maybe my IT people didn't download the correct java 8 for me. In the article you send me, it seems that I need JDK instead of JRE. The Java 8 installed on my pc is: C:\Program Files (x86)\Java\jre1.8.0_101. I'm thinking maybe I should install JDK instead?

Thank you and have a nice one!

Best regards,
Sunny

**Comment by sunny2nyc** [comment]
Sorry I keep asking stupid question, if I asked them to update my system variable as:

![image](https://cloud.githubusercontent.com/assets/22156610/18454116/9983858c-7910-11e6-965c-789c0fe37798.png)

will things work properly?

**Comment by maxcorbin** [comment]
Hey @sunny2nyc, this doesn't seem like a LookR problem anymore, so I'm probably going to close this issue. I'm not qualified to give you advice on how to get your data back into your database from R. Please bring this question to StackOverflow or some other website for general programming advice.

**Comment by sunny2nyc** [comment]
Hi @maxcorbin, thank you so much for your help! It's all good now. I have installed lookr. I'll google the rest of the codes I need. Have a nice one!

**Comment by sunny2nyc** [comment]
Morning Maxie,

Thank you so much for your help! I have installed lookR successfully on my computer. I tried to bring data from looker using below R scripts:

library("rJava")
library("RJSONIO")
library("LookR")

looker_setup(id="hrD84CCz4VHrrJppnMJq", secret= "fmzq7y6hv7C9JsSctMQBHmBw", api_path="https://arkadium.looker.com:19999")
gettrainingdata = function(){
print("Getting data")
returnvalue=run_inline_query(model="arena",
                              view = "google_analytics_sessions_daily_by_adtestslot2",
                              fields = c(
                              "google_analytics_sessions_daily_by_adtestslot2.date_date",
                              "google_analytics_sessions_daily_by_adtestslot2.starts_per_user"
                              ),
                              filters = list(
                              c("google_analytics_sessions_daily_by_adtestslot2.custdim02_adslot2","quiz_preroll_midroll_test_A")
                              )
)
print("Done.")
return(returnvalue)
}

Scripts can run successfully. But when I try to call this function to print data. I got below message:

[cid:image001.png@01D20DA8.02A9E080]

It seems below step is getting error:
[cid:image002.png@01D20DA8.02A9E080]

Maybe it’s related to my account info? Could you help advise on this? Thank you and please let me know!

Have a nice one!

Best regards,
Sunny


SUNNY ZHU

ARKADIUM   │  BI Data Analyst
───────────────────────────────────────────
40 West 25th St., 4th FLOOR   │   NEW YORK, NY 10010
Cell 347-557-7345
www.arkadium.com<http://www.arkadium.com/>
