### ISSUE TITLE
RJavaTools error

### ISSUE THREAD

**Issue by shawnconnor** [looker/lookr#15]
When running on windows, I receive the following error when running looker_setup:
```
> my_look <- run_look(90)
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I believe this has to do with local java certs and I am looking into it based on [these](https://www.mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/) instructions. Will update if I find out more.

**Comment by maxcorbin** [comment]
@shawnconnor Let me know if the java certs were the problem, I hope that is the case!

**Comment by shawnconnor** [comment]
Those instructions didn't work, got as far as running the java file and it threw a string of exceptions. I still suspect the certs are the problem but I'm not sure how to resolve it.

**Comment by shawnconnor** [comment]
I was able to successfully connect. For the benefit of anyone else who runs into this, I had to:
- Download the cert file from our internally-hosted Looker site using a browser (I used chrome)
- Running from an admin-mode command prompt, use keytool import to add that cert to my cacerts, one at a time (presumably R only uses one but I didn't know which, so I did them all; 32 and 64 bit, jdk and jre, so 4 total)
