### ISSUE TITLE
Make non-json content query-able

### ISSUE THREAD

**Issue by snarron** [looker/lookr#4]
Can't pull non-json results today. Would be great if we could.

From lookr/src/main/gen/io/swagger/client/ApiClient.java
```
  /**
   * Serialize the given Java object into string according the given
   * Content-Type (only JSON is supported for now).
   */
  public String serialize(Object obj, String contentType) throws ApiException {
    if (contentType.startsWith("application/json")) {
      return json.serialize(obj);
    } else {
      throw new ApiException(400, "can not serialize object into Content-Type: " + contentType);
    }
  }
```

**Comment by githoov** [comment]
@snarron What did you have in mind? At present, I convert all queries into an R data frame directly, which is sort of the default data structure for R. What sort of data structure would you like to see?

**Comment by snarron** [comment]
@githoov

So, the function run_look() allows the developer to pick a format through
the format arg. The default is json, as you know. Once you change the
format (e.g. run_look(602, format=”csv”)), you get the following error:

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  :
io.swagger.client.ApiException: can not deserialize Content-Type:
text/plain;charset=utf-8

That’s where the request came from. Would be great if we could maybe do
some like:

read.csv(runlook(602,format="csv"))

Also, the result-to-dataframe conversion works for R, but not others like
python (obviously not supported for now anyway).
​

**Comment by githoov** [comment]
`read.csv(run_look(602,format="csv"))` will create a data.frame, which run_look(602) already does.

**Comment by snarron** [comment]
in that case we probably should make it clear that you shouldn't pass values through the format arg? maybe i read too much into what i can pass through the function.

**Comment by githoov** [comment]
@snarron So—you're looking at the Swagger-generated Java. I'd expect most users to follow the README for this repo. And in that document, it's pretty clear, in my opinion, that neither `run_look` nor `run_inline_query` take data-type parameters. However, I can add this to the documentation to be clear. Would that help?

**Comment by snarron** [comment]
@githoov

That's fair enough - no worries for now. I don't think customers trying to
use LookR would get deep into the Java code anyway.

Thanks!
