### ISSUE TITLE
run_look does not handle 0's well

### ISSUE THREAD

**Issue by lawwu** [looker/lookr#6]
If an output cell in Looker is empty, it looks like Looker fills in that empty cell with whatever was in the first column. This is the warning message below:

```
Warning message:
In rbind(c("2014-11", "3"), c("2014-12", "84", "99", "16"), c("2015-01",  :
  number of columns of result is not a multiple of vector length (arg 1)
```

**Comment by githoov** [comment]
@lawwu Could you provide a bit more context in order to reproduce please? For instance, what is the look returning? How many and what type of dimensions, measures, pivots, filters, etc? What is the expected response data format?

Thanks!

**Comment by lawwu** [comment]
I pulled a Look that has 1 dimension (month), 4 measures and 1 pivoted dimension. Filtering the pivoted dimension to only show 4 values and filter the month for the latest year.

 In Looker I've confirmed that the first row should only have one of the measures populated. But in R when using run_look, the data isn't carrying over. I can share screenshots if that'd be helpful.

**Comment by githoov** [comment]
@lawwu If you don't mind sharing an image, that'd be very useful. Please obfuscate any potentially sensitive data of course.

**Comment by lawwu** [comment]
It seems like if a value is null, the run_look function is filling in that null value with whatever is in the first column:

![looker output](https://cloud.githubusercontent.com/assets/9869041/12790327/a09c11fe-ca56-11e5-9cf3-fb12daa427a9.png)
![r output](https://cloud.githubusercontent.com/assets/9869041/12790329/a12ac2fa-ca56-11e5-8562-1e89e653abac.png)

**Comment by githoov** [comment]
@lawwu This should be resolved. You can update your LookR version by running `install_github("looker/lookr")`. You should see that we're using the RJSONIO library rather than rjson. That seems to have done the trick. Thanks, @thekenz for the change.
